services:
  web:
    image: nginx:alpine
    ports:
      - "8049:80"  # Проброс порта 8049 на 80
    networks:
      - frontend-net
    volumes:
      - type: bind
        source: ./nginx/app.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./nginx/index.html
        target: /usr/share/nginx/html/index.html
        read_only: true
      - type: bind
        source: ./nginx/styles.css
        target: /usr/share/nginx/html/styles.css
        read_only: true
      - type: bind
        source: ./nginx/script.js
        target: /usr/share/nginx/html/script.js
        read_only: true
    depends_on:
      - simple_python_app

  simple_python_app:
    image: simple_python_app:latest
    build: ./simple_python_app  # Убедитесь, что у вас есть Dockerfile в этой директории
    environment:
      API_DB_HOST: db
      API_DB_PASS: apipass
      API_DB_NAME: api
      API_DB_USER: apiuser
    networks:
      - frontend-net
      - backend-net
    ports:
      - "5000:8000"  # Проброс порта 5000 на 8000 (порт, на котором работает Uvicorn)
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_PASSWORD: apipass
      POSTGRES_DB: api
      POSTGRES_USER: apiuser
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
      start_interval: 1s

networks:
  frontend-net:
  backend-net:

volumes:
  dbdata:

